[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.3.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"

[rpc_endpoints]
base = "https://mainnet.base.org"

baseSepolia = "https://sepolia.base.org"
devnet = "${TENDERLY_DEVNET_RPC}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url="https://api.basescan.org/api" }

baseSepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url="https://api-sepolia.basescan.org/api" }
devnet = { key = "${TENDERLY_API_KEY}", url = "${TENDERLY_DEVNET_RPC}/verify/ethers" }